Propuesta condensada layout principal
omegaup/blog pull request #41
Opened 2024-12-16 20:15 UTC by IsmaelSantanaR

@tvanessa seguí tu sugerencia de un formato mas simple y adapté el template de Hextra al documento de diseño.

Quedo atento a sus comentarios.

![image](https://github.com/user-attachments/assets/d2872845-d4a7-4967-9132-d02806b810c2)

2024-12-16 21:05 UTC, IsmaelSantanaR commented
Se agrega propuesta página de comienza en omegaUp

![image](https://github.com/user-attachments/assets/d43d465f-6a76-4f28-b699-f17c9557eacb)

2024-12-26 20:10 UTC, IsmaelSantanaR commented
![image](https://github.com/user-attachments/assets/3922aeda-3024-45c3-a89f-d7179bf6529d)

2025-01-02 18:56 UTC, tvanessa requested changes
Te dejo algunas observaciones:

![blog](https://github.com/user-attachments/assets/960998c7-e270-4fa5-9887-f8c1a0aa97c5)

2025-01-02 18:56 UTC, tvanessa commented on content/Comienza.md
> +- Se el mejor [reglas del coder del mes](/posts/reglas-del-coder-del-mes/)
Necesitamos que no tenga género
```suggestion
- Participa para ser Coder del Mes [reglas del coder del mes](/posts/reglas-del-coder-del-mes/)
```

2025-01-07 01:43 UTC, IsmaelSantanaR commented
## Propuesta página principal:

![image](https://github.com/user-attachments/assets/05041e0d-2deb-40ce-bf81-942c67940189)

## Página secundaria "Comienza"

![image](https://github.com/user-attachments/assets/575ce743-a04f-4445-a68e-3c76b22051ac)

## Página secundaria "Novedades".
Está doble las secciones en texto e imágenes, en lo personal prefiero con imágenes.

![image](https://github.com/user-attachments/assets/c880c89e-5b5c-41fc-9967-7420a90391f2)

2025-01-08 09:08 UTC, heduenas commented
@IsmaelSantanaR gracias por los screenshots. Habías mencionado que el problema con poner las listas de ligas en las cajitas era que iban a ser listas muy largas, correcto? Sí hay que poner las listas de ligas pero sólo con unas 4 o 5 ligas cada una y una de "Ver más" que te lleve a una página separada con la lista completa de ligas. De esa manera no se va a saturar de ligas las cajitas.

2025-01-13 22:06 UTC, IsmaelSantanaR commented
![image](https://github.com/user-attachments/assets/969573f9-ff25-4603-b63c-543a56a7266a)

2025-01-15 08:19 UTC, heduenas commented on content/Comienza.md
> +  {{< card link="https://github.com/omegaup/omegaup/wiki" title="Agrega documentación " icon="card" >}}
Hay que remover esta liga. Pronto vamos a incorporar la documentacion al repositorio como codigo y dejar de usar la funcionalidad de wiki.

2025-01-15 08:20 UTC, heduenas commented
@IsmaelSantanaR hay que ponerle bullets a las listas y remover un card que te pido en el otro comentario y ya le podemos dar merge.

2025-01-15 16:13 UTC, IsmaelSantanaR commented
# Propuesta modo claro:
![image](https://github.com/user-attachments/assets/ed124fb6-a82a-4a2e-a0f8-fb8d49a6c53f)

# Propuesta modo oscuro:
![image](https://github.com/user-attachments/assets/04547474-7f9b-40e6-9d9d-787a91b31968)

2025-01-20 22:31 UTC, heduenas approved these changes

2025-01-20 22:37 UTC, tvanessa commented
Puedes borrar las imagenes que ya no se van a usar y le damos merge?

2025-01-20 23:30 UTC, IsmaelSantanaR commented
> Puedes borrar las imagenes que ya no se van a usar y le damos merge?

Ok listo

2025-01-20 23:31 UTC, tvanessa approved these changes

2025-01-20 23:31 UTC, merged